language: go

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_ef8c2c06311c_key -iv $encrypted_ef8c2c06311c_iv -in client-secret.json.enc -out client-secret.json -d

install:
  - nvm install 13
  - npm install

before_script:
  - node --version

script:
  - npm run build
  - GO111MODULE=on ( cd app/web && go get )

deploy:
  provider: gae
  keyfile: client-secret.json
  project: sns-taka3sh-org-157419
  config: app/web/app.yaml
  skip_cleanup: true
