language: go

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_ef8c2c06311c_key -iv $encrypted_ef8c2c06311c_iv -in client-secret.json.enc -out client-secret.json -d

install:
  - nvm install 13
  - npm install

before_script:
  - node --version

script:
  - npm run build
  - ( cd app && go get )

after_success:
  - mkdir -p gopath/src/github.com/taka3sh
  - ln -s $PWD gopath/src/github.com/taka3sh/sns.taka3sh.org

deploy:
  provider: gae
  keyfile: client-secret.json
  project: sns-taka3sh-org-157419
  skip_cleanup: true
