application: sns-taka3sh-org-157419
version: 1
runtime: go
api_version: go1
skip_files:
- (?!^(app|public))

handlers:

- url: /publish
  script: _go_app

- url: /publish\.dev
  script: _go_app

- url: /subscribe/.*
  script: _go_app

- url: /subscribe\.dev/.*
  script: _go_app

- url: /index\.html
  script: _go_app

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /
  static_dir: public
