application: sns-taka3sh-org-157419
version: 1
runtime: go
api_version: go1
skip_files:
- (?!^(app|www))

handlers:

- url: /publish/.*
  script: _go_app

- url: /subscribe/.*
  script: _go_app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_dir: www