steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - functions
      - deploy
      - Publish
      - --region=asia-northeast1
      - --source=.
      - --runtime=go113
      - --trigger-http
      - --allow-unauthenticated
      - --security-level=secure-always
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - functions
      - deploy
      - PublishDev
      - --region=asia-northeast1
      - --source=.
      - --runtime=go113
      - --trigger-http
      - --allow-unauthenticated
      - --security-level=secure-always
    waitFor: ['-']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - functions
      - deploy
      - Subscribe
      - --region=asia-northeast1
      - --source=.
      - --runtime=go113
      - --trigger-http
      - --allow-unauthenticated
      - --security-level=secure-always
    waitFor: ['-']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - gcloud
      - functions
      - deploy
      - SubscribeDev
      - --region=asia-northeast1
      - --source=.
      - --runtime=go113
      - --trigger-http
      - --allow-unauthenticated
      - --security-level=secure-always
    waitFor: ['-']
