name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Build
      run: go build -v .

    - name: Install staticcheck
      run: go get honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck
